site_name: Tadpoly Developer Documentation
site_description: Documentation for the Tadpoly console
site_url: https://tadpoly.net/

theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - content.code.copy

extra_css:
  - stylesheets/tadpoly.css

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.highlight:
      anchor_linenums: true

extra:
  generator: false

copyright: >
  &copy; 2026 Tadpoly. Released under the MIT License.